### ISSUE TITLE
Problémy zbylé z vývoje úvodních e-learningů

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/data.gov.cz#177]
- [ ] V některých případech, je obrázek umístěn pod textem i když by mohl být úmístěn na pravé straně. https://opendata-mvcr.github.io/skoleni-test/modul-07/index.html#/19/0/1 (starý link)
- [ ] V https://opendata-mvcr.github.io/skoleni-test/modul-05/index.html#/6/0/1 je odkaz pomocí obrázku. Nebylo by lepší dát odkaz jako text nad obrázkem a obrázek nechat bez akce? Text nad obrázkem je "Prohlédněte si je!" (starý link)
- [ ] Některé obrázky mají malé rozlišení na to, aby bylo možné je dostatečně zvětšit - otázka je, jak moc je chcem zvětšovat, příklad 
https://opendata-mvcr.github.io/skoleni-test/modul-04/index.html#/7 , obrázek má velikost kolem 800x300. (starý link)
- [ ] Můžeme vylepšit odkazování na zdroje: příklad modul7 , ```Zdroj: tsk-praha.cz```. By mohl:
  * Být odkaz
  * Odkazovat na konkríétní stránku / obrázek
  * Obsahovat informaci o času přístupu
- [ ] Ve slajdech se aktuálně hojně využívá fragmentů, tedy postupné zobrazní prvků, zejména textu. Nicméně to poněkud zpomaluje rychlejší prohlížení. Možná by bylo zajímvé prozkoumat možnost, jak fragmenty "deaktivovat" a vidět tak vždy rovnou plný slide.
- [ ] Pro každý obrázek bychom měli mít informaci o je ho zdroji, například README file s odkazy. Nejen kvůli "citaci" zdroje, ale případně i pro kontrolu licence použití.

**Comment by skodapetr** [comment]
- [] Příliš velký obrázek na https://opendata-mvcr.github.io/vzdělávání/e-learning/co-jsou-otevřená-data/co-jsou-to-otevřená-data/#/1/0/0
- [] Odkaz obrázkem na https://opendata-mvcr.github.io/vzdělávání/e-learning/co-jsou-otevřená-data/co-jsou-to-otevřená-data/#/5/0/2
- [] Odkaz obrázkem https://opendata-mvcr.github.io/vzdělávání/e-learning/co-jsou-otevřená-data/co-jsou-to-otevřená-data/#/10/0/0
- [] Černý text na černém pozadí na https://opendata-mvcr.github.io/vzdělávání/e-learning/co-jsou-otevřená-data/znovupoužitelnost-a-interoperabilita/#/17/0/1
- [] Odkaz obrázkem https://opendata-mvcr.github.io/vzdělávání/e-learning/co-jsou-otevřená-data/katalogizace-otevřených-dat/#/2/0/1
- [] Odkaz obrázkem https://opendata-mvcr.github.io/vzdělávání/e-learning/co-jsou-otevřená-data/katalogizace-otevřených-dat/#/8/0/0
- [] Odkaz obrázkem https://opendata-mvcr.github.io/vzdělávání/e-learning/co-jsou-otevřená-data/kontext-otevřených-dat-v-čr/#/3/0/1
- [] Zvětšit obrázek https://opendata-mvcr.github.io/vzdělávání/e-learning/publikační-plán-a-publikace-dat/úvod-do-kurzu/#/5
- [] Zvětšit obrázek https://opendata-mvcr.github.io/vzdělávání/e-learning/publikační-plán-a-publikace-dat/otevírání-dat-jeden-z-procesů-organizace/#/2
- [] Zvětšit obrázek https://opendata-mvcr.github.io/vzdělávání/e-learning/publikační-plán-a-publikace-dat/role-v-procesu-otevírání-dat-v-organizaci/#/7
- [] Zvětšit obrázek https://opendata-mvcr.github.io/vzdělávání/e-learning/publikační-plán-a-publikace-dat/role-v-procesu-otevírání-dat-v-organizaci/#/12
- [] Zvětšit obrázek https://opendata-mvcr.github.io/vzdělávání/e-learning/publikační-plán-a-publikace-dat/role-v-procesu-otevírání-dat-v-organizaci/#/16
- [] Zvětšit obrázek  https://opendata-mvcr.github.io/vzdělávání/e-learning/publikační-plán-a-publikace-dat/role-v-procesu-otevírání-dat-v-organizaci/#/18
- [] Odkaz obrázkem https://opendata-mvcr.github.io/vzdělávání/e-learning/publikační-plán-a-publikace-dat/interní-legislativa-v-oblasti-od/#/6/0/1
- [] Odkaz obrázkem https://opendata-mvcr.github.io/vzdělávání/e-learning/publikační-plán-a-publikace-dat/podmínky-užití/#/11/0/0
