### ISSUE TITLE
první krok při otevírání dat

### ISSUE THREAD

**Issue by RadkaDomanska** [datagov-cz/data.gov.cz#227]
Připomínka od Radan Březa (NAKIT):
•	Slide „Jak na otevření data – Krok 1“  První odrážka je podle mě špatně, cituji: Na úvod musíme zvolit vhodnou datovou sadu – například takovou, která souvisí s hlavními agendami dané instituce – nejčastěji ji vyexportujeme z IS organizace. Tohle je technokratický pohled. Je třeba začít business úvahou, jaká data mám a jaká budu poskytovat , ať už přímo, nebo anonymizovaně, nebo je budu agregovat. To, že je musím vytáhnout z nějakého datového modelu je až další krok.

**Comment by martinvita** [comment]
Tenhle modul chce v zásadě sdělit, že otevírání dat může být relativně jednoduchá záležitost, nic víc, nic míň. Je zacílen spíš na situaci, kdy je v organizaci nálada "pojďme něco otevřít, prošťouchneme to...a pak se na to podíváme systematicky". Na to první cílí tenhle modul, na tu druhou, systematickou část pak cílí ten kurz, který je zmíněn později – "Publikační plán..."
Já bych to osobně nechal tak, jak to je, ale rád si poslechnu i názory dalších @RadkaDomanska , ...
