### ISSUE TITLE
Divná formulace u interoperability

### ISSUE THREAD

**Issue by martinnec** [datagov-cz/data.gov.cz#236]
Upravit formulaci - "standardů" češtinářsky nesedí https://data.gov.cz/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/co-jsou-otev%C5%99en%C3%A1-data/co-jsou-to-otev%C5%99en%C3%A1-data/#/15/0/2

**Comment by martinvita** [comment]
@martinnec – co kdyby to bylo "využíváním standardů, otevřených formátů a strojovou čitelností"? Zní to lépe? Nebo to chceme i významově posunout?
