### ISSUE TITLE
V NKODu není aktualizovaná NKODka

### ISSUE THREAD

**Issue by bindeali** [datagov-cz/data.gov.cz#449]
V patičce české i anglické verze NKODu (tj. ne POD jako takový, ale jeho sekce https://data.gov.cz/datov%C3%A9-sady) není aktualizovaná NKODka. Přetrvává i po smazání cache v několika prohlížečích. Ve zdrojovém kódu ale chyba není, tam je vše správně (možná kromě telefonu v anglické patičce).

**Comment by jakubklimek** [comment]
Datasety, aplikace atd. nejsou součástí webu, ale separátní aplikace (https://github.com/datagov-cz/nkod-registrovane-aplikace), takže je to tam třeba aktualizovat zvlášť, což jsem provedl.

**Comment by bindeali** [comment]
Vyřešení problému potvrzuji, zavírám.
